config/routes.rb
Rails.application.routes.draw do
  resources :customers

  resources :tickets

  resources :routes

  resources :trips

  resources :maintenances

  resources :crews

  resources :trains

  root 'routes#index'

  get 'sales' => 'tickets#sales'

end

app/models/crew.rb
class Crew < ActiveRecord::Base
  has_many :maintenances
  validates :given_name, :middle_name, :last_name, presence: true

  def to_s 
    "#{given_name} #{last_name}"
  end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: [:show, :edit, :update, :destroy]

  # GET /crews
  # GET /crews.json
  def index
    @crews = Crew.all
  end

  # GET /crews/1
  # GET /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews
  # POST /crews.json
  def create
    @crew = Crew.new(crew_params)

    respond_to do |format|
      if @crew.save
        format.html { redirect_to @crew, notice: 'Crew was successfully created.' }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1
  # PATCH/PUT /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to @crew, notice: 'Crew was successfully updated.' }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1
  # DELETE /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to crews_url, notice: 'Crew was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crew_params
      params.require(:crew).permit(:last_name, :given_name, :middle_name)
    end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/crews/_form.html.erb
<%= form_for(@crew, html: {class: "form-horizontal"}) do |f| %>
  <% if @crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% @crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :given_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :given_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing crew</h1>

<%= render 'form' %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<h1>Listing crews</h1>

<table class="table">
  <thead>
    <tr>
      <th>Last name</th>
      <th>Given name</th>
      <th>Middle name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.last_name %></td>
        <td><%= crew.given_name %></td>
        <td><%= crew.middle_name %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_crew_path %>

app/views/crews/new.html.erb
<h1>New crew</h1>

<%= render 'form' %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>
<h1 style="text-align:center;">Ticket Information</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 center">
    <p>
      <strong>
        CREW ID: <%= @crew.id %>
      </strong>
    </p>
       
    </div>
    <div class="col-md-6 center">

    <p>
      <strong>
        CREW NAME: <%= @crew %>
      </strong>
    </p>
    </div>
  </div>
</div>
<h1 style="text-align:center;">TRIP ITINERARY</h1>
<table class="table">
  <thead>
    <tr class="center">
      <th>Date</th>
      <th>Train ID</th>
      <th>Task</th>
    </tr>
  </thead>

  <tbody>
    <% @crew.maintenances.each do |maintenance| %>
      <tr>
        <td><%= maintenance.maintenance_date %></td>
        <td><%= maintenance.train.id %></td>
        <td><%= maintenance.task %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>