config/routes.rb
Rails.application.routes.draw do
  resources :customers

  resources :tickets

  resources :routes

  resources :trips

  resources :maintenances

  resources :crews

  resources :trains

  root 'routes#index'

  get 'sales' => 'tickets#sales'

end

app/models/train.rb
class Train < ActiveRecord::Base
  has_many :maintenances
  has_many :trips
  validates :model, presence: true
  validates :no_of_seats, :no_of_toilets, numericality: { only_integer: true }

  def to_s
    "#{id} - #{model}"
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
    @maintenances = @train.maintenances
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:model, :max_speed, :no_of_seats, :no_of_toilets, :reclining_seats, :folding_tables, :disability_access, :luggage_storage, :vending_machines, :food_service)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :max_speed %><br>
    <%= f.number_field :max_speed %>
  </div>
  <div class="field">
    <%= f.label :no_of_seats %><br>
    <%= f.number_field :no_of_seats %>
  </div>
  <div class="field">
    <%= f.label :no_of_toilets %><br>
    <%= f.number_field :no_of_toilets %>
  </div>
  <div class="field">
    <%= f.label :reclining_seats %><br>
    <%= f.check_box :reclining_seats %>
  </div>
  <div class="field">
    <%= f.label :folding_tables %><br>
    <%= f.check_box :folding_tables %>
  </div>
  <div class="field">
    <%= f.label :disability_access %><br>
    <%= f.check_box :disability_access %>
  </div>
  <div class="field">
    <%= f.label :luggage_storage %><br>
    <%= f.check_box :luggage_storage %>
  </div>
  <div class="field">
    <%= f.label :vending_machines %><br>
    <%= f.check_box :vending_machines %>
  </div>
  <div class="field">
    <%= f.label :food_service %><br>
    <%= f.check_box :food_service %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<h1>Listing trains</h1>

<table class="table">
  <thead>
    <tr>
      <th>Model</th>
      <th>Max speed</th>
      <th>No of seats</th>
      <th>No of toilets</th>
      <th>Reclining seats</th>
      <th>Folding tables</th>
      <th>Disability access</th>
      <th>Luggage storage</th>
      <th>Vending machines</th>
      <th>Food service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.model %></td>
        <td><%= train.max_speed %></td>
        <td><%= train.no_of_seats %></td>
        <td><%= train.no_of_toilets %></td>
        <td><%= train.reclining_seats %></td>
        <td><%= train.folding_tables %></td>
        <td><%= train.disability_access %></td>
        <td><%= train.luggage_storage %></td>
        <td><%= train.vending_machines %></td>
        <td><%= train.food_service %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>
<h1 style="text-align:center;">Train Maintenance Information</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 center">
    <p>
      <strong>
        TRAIN ID: <%= @train.id %>
      </strong>
    </p>
    <p>
      <strong>
        MAX SPEED: <%= @train.max_speed %>
      </strong>
    </p>
    <p>
      <strong>
        RECLINING SEATS: <%= yn(@train.reclining_seats).upcase %>
      </strong>
    </p>
    <p>
      <strong>
        LUGGAGE STORAGE: <%= yn(@train.luggage_storage).upcase %>
      </strong>
    </p>
    </div>
    <div class="col-md-4 center">
    <p>
      <strong>
        MODEL: <%= @train.model.upcase %>
      </strong>
    </p>
    <p>
      <strong>
        NO. OF SEATS: <%= @train.no_of_seats %>
      </strong>
    </p>
    <p>
      <strong>
        FOLDING TABLES: <%= yn(@train.folding_tables).upcase %>
      </strong>
    </p>
    <p>
      <strong>
        VENDING MACHINES: <%= yn(@train.vending_machines).upcase %>
      </strong>
    </p>
    </div>
    <div class="col-md-4 center">
    <p>
      <br>
    </p>
    <p>
      <strong>
        NO. OF TOILETS: <%= @train.no_of_toilets %>
      </strong>
    </p>
    <p>
      <strong>
        DISABILITY ACCESS: <%= yn(@train.disability_access).upcase %>
      </strong>
    </p>
    <p>
      <strong>
        FOOD SERVICE: <%= yn(@train.food_service).upcase %>
      </strong>
    </p>
    </div>
  </div>
</div>
<h1 style="text-align:center;">Maintenance History</h1>
<table class="table">
  <thead>
    <tr class="center">
      <th>Date</th>
      <th>Crew In Charge</th>
      
      <th>Task</th>
      <th>Condition</th>

    </tr>
  </thead>

  <tbody>
    <% @maintenances.each do |maintenance| %>
      <tr>
        <td><%= maintenance.maintenance_date.strftime('%B %e, %Y') %></td>
        <td><%= maintenance.crew %></td>
       
        <td><%= maintenance.task %></td>
        <td><%= maintenance.condition %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_train_path(@train), class: "btn btn-primary" %> |
<%= link_to 'Back', trains_path, class: "btn btn-primary" %> |
<%= link_to 'New Maintenance', new_maintenance_path(train_id: @train.id), class: "btn btn-primary" %>