config/routes.rb
Rails.application.routes.draw do
  resources :customers

  resources :tickets

  resources :routes

  resources :trips

  resources :maintenances

  resources :crews

  resources :trains

  root 'routes#index'

  get 'sales' => 'tickets#sales'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :tickets
  validates :given_name, :middle_name, :last_name, :birthdate, :gender, presence: true

  def to_s
    "#{given_name} #{last_name}"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:given_name, :middle_name, :last_name, :birthdate, :gender)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, html: {class: "form-horizontal"}) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :given_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :given_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gender, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :gender, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birthdate, class: "col-sm-2 control-label" %><br>
    <div class="col-sm-10">
      <div class="col-sm-4">
        <%= f.date_select :birthdate, {:start_year => 1900, :end_year => 2015, date_separator: "</div><div class='col-sm-4'>"}, {class: "form-control"} %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Given name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Birthdate</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.given_name %></td>
        <td><%= customer.middle_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.birthdate %></td>
        <td><%= customer.gender %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<h1 style="text-align:center;">Customer Information</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 center">
    <p>
      <strong>
        CUSTOMER ID: <%= @customer.id %>
      </strong>
    </p>
    <p>
      <strong>
        LAST NAME: <%= @customer.last_name.upcase %>
      </strong>
    </p>
    <p>
      <strong>
        BIRTH DATE: <%= @customer.birthdate.strftime("%B %e, %Y").upcase %>
      </strong>
    </p>
    
    </div>
    <div class="col-md-4 center">
    <p>
      <br />
    </p>
    <p>
      <strong>
        GIVEN NAME: <%= @customer.given_name.upcase %>
      </strong>
    </p>
    <p>
      <strong>
        GENDER: <%= @customer.gender.upcase %>
      </strong>
    </p>
    </div>
    <div class="col-md-4 center">
    
    <p>
      <strong>
        MIDDLE NAME: <%= @ticket.customer.middle_name.upcase %>
      </strong>
    </p>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>