config/routes.rb
Rails.application.routes.draw do
  resources :customers

  resources :tickets

  resources :routes

  resources :trips

  resources :maintenances

  resources :crews

  resources :trains

  root 'routes#index'

  get 'sales' => 'tickets#sales'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TirianTrains</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="full">
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Tirian Trains</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= is_active?(trains_path) %>"><%= link_to "Trains", trains_path %></li>
            <li class="<%= is_active?(maintenances_path) %>"><%= link_to "Maintenance", maintenances_path %></li>
            <li class="<%= is_active?(trips_path) %>"><%= link_to "Trips", trips_path %></li>
            <li class="<%= is_active?(routes_path) %>"><%= link_to "Routes", routes_path %></li>
            <li class="<%= is_active?(tickets_path) %>"><%= link_to "Tickets", tickets_path %></li>
            <li class="<%= is_active?('sales') %>"><%= link_to "Sales Report", "/sales" %></li>
           
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <div class="layer">
    <%= yield %>
  </div>

</body>
</html>